# Generated by Django 4.2.24 on 2025-10-03 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0005_alter_audio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='عنوان پرامپت', max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(help_text='محتوای پرامپت', verbose_name='محتوا')),
                ('is_active', models.BooleanField(default=True, help_text='فعال یا غیرفعال', verbose_name='فعال')),
                ('type', models.ForeignKey(help_text='نوع پرامپت', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='files.subset', verbose_name='نوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرامپت',
                'verbose_name_plural': 'پرامپت\u200cها',
            },
        ),
    ]
