import logging
import time


class RequestLoggingMiddleware:
    """Middleware that logs request metadata and execution duration for observability."""

    def __init__(self, get_response):
        """Initialize the middleware with the Django response callable.

        Args:
            get_response (Callable): The next middleware or view callable in the chain.
        """
        self.get_response = get_response
        self.logger = logging.getLogger('requests')

    def __call__(self, request):
        """Capture timing and user context around each request and emit a structured log entry.

        Args:
            request (HttpRequest): Incoming HTTP request to process.

        Returns:
            HttpResponse: Response generated by downstream middleware or view.
        """
        start_time = time.time()
        response = self.get_response(request)
        duration_ms = int((time.time() - start_time) * 1000)

        user_id = getattr(getattr(request, 'user', None), 'id', None)
        self.logger.info(
            'method=%s path="%s" status=%s duration_ms=%s user_id=%s ip=%s',
            request.method,
            request.get_full_path(),
            getattr(response, 'status_code', None),
            duration_ms,
            user_id,
            request.META.get('REMOTE_ADDR')
        )
        return response





