# Generated by Django 5.2.4 on 2025-08-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='file_type',
            field=models.CharField(choices=[('S', 'صورت جلسه'), ('L', 'درس آموخته')], default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='subject',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='status',
            field=models.CharField(choices=[('P', 'در انتظار'), ('A', 'تایید شده'), ('Pr', 'در حال پردازش'), ('R', 'رد شده')], default='P'),
        ),
        migrations.AddField(
            model_name='audio',
            name='subset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='files.subset'),
            preserve_default=False,
        ),
    ]
