# Generated by Django 5.2.4 on 2025-08-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_subset_audio_file_type_audio_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subset',
            old_name='titel',
            new_name='title',
        ),
    ]
