# Generated by Django 5.2.4 on 2025-08-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_titel_subset_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_type',
            field=models.CharField(choices=[('S', 'صورت جلسه'), ('L', 'درس آموخته')], max_length=2),
        ),
        migrations.AlterField(
            model_name='audio',
            name='status',
            field=models.CharField(choices=[('P', 'در انتظار'), ('A', 'تایید شده'), ('Pr', 'در حال پردازش'), ('R', 'رد شده')], default='P', max_length=2),
        ),
    ]
