# Generated by Django 4.2.24 on 2025-10-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_audio_file_type_alter_audio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='status',
            field=models.CharField(choices=[('P', 'در انتظار'), ('A', 'تایید شده'), ('Pr', 'در حال پردازش هوشمند'), ('Pd', 'محتوای تولید شده'), ('R', 'رد شده')], default='P', max_length=2),
        ),
    ]
