# Generated by Django 4.2.24 on 2025-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_audio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True),
        ),
    ]
