# Generated by Django 5.2.4 on 2025-08-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('files', '0002_subset_audio_file_type_audio_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFileText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_orginal', models.TextField()),
                ('custom_content', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='files.audio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Keyword', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.subset')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
