# Generated by Django 4.2.24 on 2025-10-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofiletext',
            name='content_orginal',
        ),
        migrations.AddField(
            model_name='audiofiletext',
            name='content_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofiletext',
            name='content_processed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
