# Generated by Django 5.2.4 on 2025-11-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_remove_audiofiletext_content_orginal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofiletext',
            name='file',
            field=models.ForeignKey(on_delete=models.CASCADE, to='files.audio'),
        ),
    ]
